name: interview_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  responsive_sizer: ^3.3.1
  dartz: ^0.10.1
  connectivity_plus: ^6.1.4
  avatar_glow: ^3.0.1
  salomon_bottom_bar: ^3.3.2
  get_it: ^8.0.3
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter_18pt-Thin.ttf
          weight: 100

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100